version: '3'
services:

  jupyter:
    build: ./cpu # select computing platform
    restart: always
    container_name: jupyterlab

    environment:

      # Configure HTTPS:
      VIRTUAL_HOST: jupyter.prateekja.in
      LETSENCRYPT_HOST: jupyter.prateekja.in
      LETSENCRYPT_EMAIL: coffee@prateekja.in

      # Use lab in place of notebook 
      JUPYTER_ENABLE_LAB: 'yes'

    volumes:
      - ".:/home/ubuntu/" # For CPU


# Connect to reverse proxy:
networks:
  default:
    external:
      name: proxy_proxy-tier 
